# modules
childProcess = require('child_process')
express = require('express')
http = require('http')
morgan = require('morgan')
ws = require('ws')
# configuration files
configServer = require('./lib/config/server')
# app parameters
app = express()
app.set 'port', configServer.httpPort
app.use express.static(configServer.staticFolder)
app.use morgan('dev')
# serve index
require('./lib/routes').serveIndex app, configServer.staticFolder
# HTTP server
http.createServer(app).listen app.get('port'), ->
  console.log 'HTTP server listening on port ' + app.get('port')
  return
#/ Video streaming section
# Reference: https://github.com/phoboslab/jsmpeg/blob/master/stream-server.js
STREAM_MAGIC_BYTES = 'jsmp'
# Must be 4 bytes
width = 480
height = 240
# WebSocket server
wsServer = new (ws.Server)(port: configServer.wsPort)
console.log 'WebSocket server listening on port ' + configServer.wsPort
wsServer.on 'connection', (socket) ->
  # Send magic bytes and video size to the newly connected socket
  # struct { char magic[4]; unsigned short width, height;}
  streamHeader = new Buffer(8)
  streamHeader.write STREAM_MAGIC_BYTES
  streamHeader.writeUInt16BE width, 4
  streamHeader.writeUInt16BE height, 6
  socket.send streamHeader, binary: true
  console.log 'New WebSocket Connection (' + wsServer.clients.length + ' total)'
  socket.on 'close', (code, message) ->
    console.log 'Disconnected WebSocket (' + wsServer.clients.length + ' total)'
    return
  return

wsServer.broadcast = (data, opts) ->
  for i of @clients
    if `this.clients[i].readyState == 1`
      @clients[i].send data, opts
    else
      console.log 'Error: Client (' + i + ') not connected.'
  return

# HTTP server to accept incoming MPEG1 stream
http.createServer((req, res) ->
  console.log 'Stream Connected: ' + req.socket.remoteAddress + ':' + req.socket.remotePort + ' size: ' + width + 'x' + height
  req.on 'data', (data) ->
    wsServer.broadcast data, binary: true
    return
  return
).listen configServer.streamPort, ->
  console.log 'Listening for video stream on port ' + configServer.streamPort
  # Run do_ffmpeg.sh from node                                                   
  childProcess.exec '../../bin/do_ffmpeg.sh'
  return
module.exports.app = app

# ---
# generated by js2coffee 2.0.4